### ISSUE TITLE
How does mapping work?

### ISSUE THREAD

**Issue by yazhinia** [CAMI-challenge/AMBER#51]
Dear developers,
          I am trying to understand the evaluation method deeper. How do you get (i) the fraction of base pairs of the genome covered in bins and (ii) overlapping in base pairs between bin and genome without mapping through sequence alignment? The input for gold-standard and final bins has only contig names and lengths but not the coordinates. Your explanation is much appreciated.

Thanks.

Best,
Yazhini

**Comment by yazhinia** [comment]
Thank you for the links, those were very helpful. I still have some queries and would really appreciate if you could address them.

(i) For mapping reads to contigs, what tool was used by binners? I find concoct used bowtie2 but did other binners use the same of it a choice made by them
(ii) How do you calculate F1 score and purity for each sample when we use pooled assembly?
(iii) Since, the number of contigs handled differs between binners, what minimum length cutoff `-n option` was used for AMBER evaluation for comparison? or whether ARI is calculated separately for each binner?

As details for the binning pipeline are yet to be added in the GitHub repository for the second challenge evaluation, I am asking for these nitty-gritties although not the right platform.

Thanks again.

**Comment by fernandomeyer** [comment]
I assume you're referring to CAMI 2 in these questions.

(i) To know what mapping tool each binner uses, you have to investigate how the binner works and possibly contact its authors. CAMI just keeps track of command lines and parameters for reproducibility. In the case of CONCOCT 1.1.0, it is a sequence of commands because the authors don't provide an automated workflow, and you just happened to see a bowtie2 command.

(ii) "CAMI1 average completeness" was the completeness used in CAMI 2.

There is no such "binning pipeline" from CAMI computing all binnings for all methods. Binners were executed individually and their details (version, parameters...) provided in the supplementary table of the paper (link above).

**Comment by yazhinia** [comment]
So it is up to the binner's choice to use their own alignment protocol.

Thank you for your explanation.
